name: polymer_element
author: Vittorio Ballestra <vittorio.ballestra@gmail.com>
homepage: https://github.com/polymer-dart
description: Polymer-2 support for Dart
environment:
    sdk: ">=1.8.0 <2.0.0"

version: 0.6.0+1
dependencies:
  js: any
  html5: ^0.0.5
